//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailGenerator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Image { get; set; }
        public string ImageAlt { get; set; }
        public string Link { get; set; }
        public string ButtonText { get; set; }
        public int NewsletterId { get; set; }
        public int RowNr { get; set; }
        public int ColumnNr { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CustomerCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> CustomerModified { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Newsletter Newsletter { get; set; }
    }
}
