//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailGenerator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsletter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Newsletter()
        {
            this.Article = new HashSet<Article>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string Introduction { get; set; }
        public string HeaderImage { get; set; }
        public string HeaderImageAlt { get; set; }
        public string HeaderImageLink { get; set; }
        public string HeaderTitle { get; set; }
        public string HeaderSubTitle { get; set; }
        public string FooterImage { get; set; }
        public string FooterImageAlt { get; set; }
        public string FooterText { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CustomerCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> CustomerModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Article { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
